version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: env
    volumes:
      - ./:/data/web
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container
      - /usr/bin:/usr/bin # mount bin to access docker exec
    environment:
      - POSTGRES_USER=myproject_web
      - USE_DOCKER=yes
      - DOCKER_SOCKET=/var/run/docker.sock
      - DOCKER_GROUP=dockerhost
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application -w 2 -b :8000
#    command: /run.sh

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

#  postgres:
#    restart: always
#    image: postgres:9.6
#    volumes:
#      - postgres_data_local:/var/lib/postgresql/data
#      - postgres_backup_local:/backups
#      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container
#    environment:
#      - POSTGRES_USER=olc_webportalv2
#    expose:
#      - "5432"

  postgres:
    restart: always
    image: postgres:9.6
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - env
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"

  genesippr:
    ports:
      - "8001:8001"
    image: "sipprverse:v0.2"
    container_name: olcwebportalv2_genesipprv2
    tty: true
    stdin_open: true
    volumes:
      - ./olc_webportalv2/media/:/sequences
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container

  bbmap:
    ports:
      - "8002:8002"
    image: "dussaultf/bbmap:v1"
    container_name: olcwebportalv2_bbmap
    tty: true
    stdin_open: true
    volumes:
      - ./olc_webportalv2/media/:/sequences
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container

  confindr:
    ports:
      - "8003:8003"
    image: "confindr:v0.2"
    container_name: olcwebportalv2_confindr
    tty: true
    stdin_open: true
    volumes:
      - ./olc_webportalv2/media/:/sequences
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container

  geneseekr:
    ports:
      - "8004:8004"
    image: "olcwebportalv2_geneseekr:v0.1"
    container_name: olcwebportalv2_geneseekr
    tty: true
    stdin_open: true
    volumes:
      - ./olc_webportalv2/media/:/sequences
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container
